CONFIG_ZMK_HID_CONSUMER_REPORT_USAGES_FULL=y
CONFIG_ZMK_ENDPOINT_DISABLE_FALLBACK=y
CONFIG_ZMK_BEHAVIOR_LOCAL_ID_TYPE_CRC16=y


CONFIG_BT_DIS_MANUF="Kinesis Corporation"
CONFIG_BT_DIS_PNP_VID=0x29EA
CONFIG_BT_DIS_PNP_PID=0x1001

CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=5
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5

CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=y
CONFIG_BT_SMP_ALLOW_UNAUTH_OVERWRITE=y
CONFIG_ZMK_BLE_PASSKEY_ENTRY=n